-- disable security status polling via DNS
setSecurityPollSuffix("")

-- all Internet except mulicast
setACL({ "0.0.0.0/1", "128.0.0.0/2", "192.0.0.0/3", "::1/128", "2000::/3", "fd19:4581:7196:1::1" })

-- reduce performance for low load instance
pc = newPacketCache(1000)
getPool(""):setCache(pc)
setRingBuffersSize(100, 5)
setMaxTCPClientThreads(3)

newServer({ address = "[::1]:53", name = "main", healthCheckMode = "up", retries = 1 })

addDOHLocal("[::1]:44353", nil, nil, "/")
addTLSLocal("[2a03:6f00:a::1:2750]:853", "/etc/dnsdist/cert/fullchain.pem", "/etc/dnsdist/cert/privkey.pem", { additionalAddresses = {"194.58.107.196:853" } })

-- Refuse incoming AXFR, IXFR, NOTIFY and UPDATE
addAction(OrRule({OpcodeRule(DNSOpcode.Notify), OpcodeRule(DNSOpcode.Update), QTypeRule(DNSQType.AXFR), QTypeRule(DNSQType.IXFR)}), RCodeAction(DNSRCode.REFUSED))
-- DoH, DoT
-- addAction(OrRule({IncomingProtocolRule("DoH"), IncomingProtocolRule("DoT")}), PoolAction(""))
addAction(AndRule({RDRule(), OrRule({DSTPortRule(44353), DSTPortRule(853)})}), PoolAction(""))
-- Drop
addAction(AllRule(), DropAction())

