$HTTP["host"] =~ "^(www\.)?host-correct\.ru\.?" {
    server.name = "www.host-correct.ru"

    ssl.pemfile = ssl_root + "/fullchain.pem"
    ssl.privkey = ssl_root + "/privkey.pem"

    accesslog.filename = ""

    url.redirect = ()
    url.access-deny = ("")

    $HTTP["host"] != "host-correct.ru" {
        url.redirect-code = 301
        url.redirect = ("^/(.*)" => "https://host-correct.ru/$1")

        url.access-deny = ()
    }

    $HTTP["url"] =~ "^/" {
        alias.url += ("/favicon.ico" => server_root + "/html/favicon.ico")
        alias.url += ("/" => server_root + "/html/host-correct.ru/")

        url.access-deny = ()
    }

    $HTTP["url"] =~ "^/dns-query" {
        proxy.server = ("" => ("powerdns" => ("host" => "::1", "port" => 44353)))
        proxy.header = ("map-urlpath" => ("/dns-query" => "/"),)

        url.access-deny = ()
    }

}

