aggressive-nsec-cache-size=8192
allow-from=127.0.0.0/8,::1/128
any-to-tcp=yes
config-dir=/etc/powerdns
dnssec=validate
ecs-add-for=
ecs-scope-zero-address=0.0.0.0
hint-file=/usr/share/dns/root.hints
local-address=127.0.0.1,::1
loglevel=3
lua-config-file=/etc/powerdns/recursor.lua
max-cache-entries=65536
max-cache-ttl=86400
max-concurrent-requests-per-tcp-connection=4
max-include-depth=2
max-mthreads=64
max-ns-address-qperq=4
max-ns-per-resolve=8
max-nsec3-hash-computations-per-query=64
max-nsec3s-per-record=8
max-packetcache-entries=32768
max-qperq=8
max-recursion-depth=8
max-signature-validations-per-query=8
max-tcp-clients=16
max-tcp-per-client=4
max-tcp-queries-per-connection=1024
max-total-msec=1000
max-udp-queries-per-round=512
minimum-ttl-override=300
network-timeout=500
non-resolving-ns-max-fails=2
non-resolving-ns-throttle-time=600
nothing-below-nxdomain=yes
nsec3-max-iterations=50
public-suffix-list-file=/usr/share/publicsuffix/public_suffix_list.dat
query-local-address=194.58.107.196,2a03:6f00:a::1:2750
quiet=yes
security-poll-suffix=
server-down-max-fails=2
server-down-throttle-time=600
server-id=disabled
stack-cache-size=32
tcp-out-max-idle-ms=1000
tcp-out-max-idle-per-auth=4
tcp-out-max-idle-per-thread=32
threads=1
udp-source-port-avoid=4791,11211

